### ISSUE TITLE
Support for management APIs

### ISSUE THREAD

**Issue by innobrig** [digitaldonkey/ethereum-php#1]
Any chance you could expand your library to include support for the management APIs (such as personal, miner, etc.)? I see you support some personal APIs  but for example the "personal_newAccount" seem to be missing. Thanks a lot for providing this, it's very useful.

**Comment by digitaldonkey** [comment]
Don't see this coming soon. Currently only [JsonRPC](https://github.com/ethereum/wiki/wiki/JSON-RPC) is on the roadmap.

**Comment by innobrig** [comment]
I'm not sure I understand. These APIs can be accessed through JsonRPC, therefore my humble request.

**Comment by digitaldonkey** [comment]
You said it "can be accessed..." Please read http://ethereum.stackexchange.com/a/3201/852

I don't see personal API implementation even on the horizon. But you're very welcome to contribute.

Have a look at eth_sign in combination with a TX signer like Metamask. You may archive what I guess you intend to archive. At first I thought that I would need the personal API too.
