### ISSUE TITLE
Illegal offset type in isset or empty --- EthDataTypePrimitive.php LINE 75

### ISSUE THREAD

**Issue by danielefavi** [digitaldonkey/ethereum-php#11]
I tried to execute the function **eth_accounts** and I got the exception
**Illegal offset type in isset or empty** in the file **EthDataTypePrimitive.php** on line **75**

    $eth = new Ethereum('http://localhost:8545');
    echo '<pre>';
    print_r($eth->eth_accounts());

The function that is giving the exception is **typeMap** because is receiving an array instead of a string.

The problem seems to be in the file **Ethereum.php** on line 152

    $is_primitive = (bool) EthDataTypePrimitive::typeMap($return_type);

where **$return_type** is an array and not a string.

I solved adding the following line of code at the beginning of the function **typeMap** but I don't think this is the best solution

    if (is_array($type) and isset($type[0])) $type = $type[0];

**Comment by digitaldonkey** [comment]
Is this related to master or dev branch?

**Comment by Cryt1c** [comment]
I had this issue on the master branch.

**Comment by danielefavi** [comment]
Master branch.
I said that my solution is not the best one because the function **typeMap** should receive the proper type.

**Comment by digitaldonkey** [comment]
Did you try the same using dev branch? I think i fixed it there.
