### ISSUE TITLE
FatalThrowableError: Call to undefined method Ethereum\Filter::getType() 

### ISSUE THREAD

**Issue by tuyen-vuduc** [digitaldonkey/ethereum-php#12]
> digitaldonkey/ethereum-php/src/Ethereum.php on line 98

```
$filter = new Filter(
            null,
            new EthBlockParam(),
            new EthData('contract_address'),
            [
                new EthData('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
                null,
                new EthData($account)
            ]
        );

        return $this->ok([
            'logs' => $this->client->eth_getLogs($filter)
        ]);
```

**Comment by digitaldonkey** [comment]
Is this related to dev or master branch?

**Comment by nimo55pl** [comment]
on dev branch when i pass any EthData|EthD to topics array, is returning error:

> Warning: substr() expects parameter 1 to be string, object given

in vendor/digitaldonkey/ethereum-php/src/EthereumStatic.php at line 246 

    public static function hasHexPrefix($str)
    {
        return substr($str, 0, 2) === '0x';
    }

**Comment by digitaldonkey** [comment]
You might not be able to pass null in the Array even is [should be possible](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter) .

See also:
http://ethereum-php.org/dev/d9/d03/class_ethereum_1_1_filter.html

I'm happy for pull requests, for me it will take a while till I fix this (and write the requires unit tests for complex data types).
