### ISSUE TITLE
function eth_workaround_eth_coinbase($val)

### ISSUE THREAD

**Issue by Cryt1c** [digitaldonkey/ethereum-php#13]
Hi @digitaldonkey ,

thanks for providing this interface and also the drupal/ethereum module!
I would like to contribute to this project too.
Currently I try to get the dev branch running on my environment but I have a problem, when I use the INFURA net because eth_coinbase is not supported by them.
I have found these workaround:

```function eth_workaround_eth_coinbase($val)
{
    // WORKAROUND: Catch a "405 Method Not Allowed'.
    if (isset($val['error']) && $val['error'] && $val['code'] == 405) {
        return '0x0000000000000000000000000000000000000000';
    } else {
        return $val;
    }
}
```

But as I see it they are not used at the moment, which breaks the drupal/ethereum module because ethereum-php throws an Exception which is not caught (Expected EthD20 at eth_coinbase (), couldn not be decoded. Value was: Array).
Where should this workaround be used? Can I help you with this? Would be happy to create a PR if you could point me into the right direction.

Thanks for your work!

**Comment by digitaldonkey** [comment]
Seems src/helpers/ethereum-client-workaround-helpers.php is not loaded. 

--> https://github.com/digitaldonkey/ethereum-php/pull/14
