### ISSUE TITLE
Unable to send bytes as argument

### ISSUE THREAD

**Issue by wmh** [digitaldonkey/ethereum-php#19]
My contract:
```
contract MyContract {
    function b1(bytes b) public pure returns (uint) {
        return b.length;
    }
    function b2(bytes32 b) public pure returns (uint) {
        return b.length;
    }
}
```

I'm able to call `b1` from browser console:
```
myContract.b1('Hello', function (e,v) { console.log(v.toNumber()) }) // 5
myContract.b1(web3.toHex('Hello'), function (e,v) { console.log(v.toNumber()) }) // 5
```

But I can't get the correct result from ethereum-php:
```
echo $myContract->b1(new EthS('Hello!!'))->val(); // 0
echo $myContract->b1(new EthD('0x48656c6c6f'))->val(); // 0
```

Instead, send bytes32 as argument to `b2` is fine:
```
echo $myContract->b2(new EthD32('0x'.md5(1).md5(1)))->val(); // 32
```

**Comment by digitaldonkey** [comment]
Interesting question. 
First type-checking is not there yet. In my opinion sending EthS to bytes should fail. 
But there might be some type conversion. Do you prefer strict typing or the approach you experienced in Javascript (is it web3js?)?

**Comment by wmh** [comment]
strict typing is fine for me.

**Comment by digitaldonkey** [comment]
I added test contract 
https://github.com/digitaldonkey/ethereum-php/commit/6603022d759f32adc9c66e4b8e28b11ab16a5454#diff-8b3c122755c30d47256bb474d6f4a020

`vendor/bin/phpunit  --filter testString SmartContractBytesTest tests/TestEthClient/Unit/SmartContractBytesTest.php`

**Comment by digitaldonkey** [comment]
Now fixed in branch refactor-datatypes
Will be merged into dev as soon as I fixed the Drupal module.
