### ISSUE TITLE
curl_setopt_array(): Unable to create temporary file

### ISSUE THREAD

**Issue by anyluck** [digitaldonkey/ethereum-php#25]
My computer is Windows10 link can link normally, but call eth_coinbase, curl_setopt_array (): Unable to create temporary file 

Call link printing is true
   $eth=new Ethereum('http://192.168.1.144:8545');
        print_r($eth);
but eth_coinbase return curl_setopt_array(): Unable to create temporary file.
$ret=$eth->eth_coinbase();
        print_r($ret);

The same commands are the same

**Comment by digitaldonkey** [comment]
Sounds like your temporary directory lacks writing permissions. 
https://github.com/guzzle/guzzle/issues/1363
