### ISSUE TITLE
Data Field

### ISSUE THREAD

**Issue by gelinger777** [digitaldonkey/ethereum-php#3]
Can I generate via your tool  the data field for transaction made to SmartContract?

**Comment by digitaldonkey** [comment]
Yes. But only primitive data types are implemented currently.

**Comment by gelinger777** [comment]
what you mean primitive? can't I make a data field which is intended to send a command to a smart contract?

**Comment by digitaldonkey** [comment]
https://github.com/ethjs/ethjs-schema#primitives
Only the Array mentioned as "primitive type" is not implemented yet.

**Comment by gelinger777** [comment]
ok thank you
