### ISSUE TITLE
Add 'status' field to transaction receipts

### ISSUE THREAD

**Issue by sebnyc** [digitaldonkey/ethereum-php#34]
A 'status' field has been added to transaction receipts with hard fork EIP609 (see [Ethereum documentation](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-31))

That would be nice to add this field to the Receipt object so that we can see it in the response of getTransactionReceipt calls.

**Comment by digitaldonkey** [comment]
Should be easy, by adding the property to the Receipt in `ethereum-php/resources/ethjs-schema.json`
and run `ethereum-php/scripts/generate-complex-datatypes.php `to regenerate the DataTypes. 

I'm looking ahead on a week of conferences, so a PR would be great, as will need some time to get on it.

**Comment by sebnyc** [comment]
Pull request submitted

**Comment by digitaldonkey** [comment]
Now I know why I made this API schema based :D
Great Thank you.
