### ISSUE TITLE
Unexpected negative quantity for transactions

### ISSUE THREAD

**Issue by sebnyc** [digitaldonkey/ethereum-php#38]
When reading transactions in the blockchain, it appears that some "value" fields of transactions are decoded as negative, whereas this data is supposed to be positive.

I see in the code that you are aware of the problem in \Ethereum\DataType\EthQ::validate()
`// @todo This might be wrong. We need to check for RLP.`
`// @see https://github.com/ethereum/wiki/wiki/RLP`

**Comment by digitaldonkey** [comment]
Can you provide a example to test against?

**Comment by sebnyc** [comment]
Sure. You can try : 
```
$tr = $eth->eth_getTransactionByHash(new EthD32("0x527e9b670536c09fe160b0c2e33728eadd7f8affae7803049fa8d8ec2d1c7cfe"));
echo $tr->value->val();
```
I currently outputs -493447593709551616 whereas the expected value is 1122081030000000000.

**Comment by sebnyc** [comment]
@digitaldonkey I'm not sure I understand how the EthQ class is used for RLP decoding, so I don't feel comfortable providing a pull request for this one.
Do you have any hint on how to fix that ?

**Comment by digitaldonkey** [comment]
My current guess is that the block number is actually not a EthQ as it is not padded as far as I remember. 
Looking into it now.

**Comment by sebnyc** [comment]
Yes I confirm that the block number is not padded, that's what I see in my tests with my Parity node.
And same thing for many other attributes (transaction value, nonce, gasPrice, gas, gasUsed, block difficulty, gasLimit,...).

**Comment by digitaldonkey** [comment]
Assuming that data types are implemented consistently was a very naive idea of mine ;)

My approach so far was to use the Library to make them consistent - independently from the actual client.

**Comment by digitaldonkey** [comment]
[Fixed in dev](https://github.com/digitaldonkey/ethereum-php/commit/8051cab97a1e986785a0489646e3071ed275051b) branch now.

**Comment by sebnyc** [comment]
@digitaldonkey Nice, thank you !
That should do the trick. Can't wait to test it.
