### ISSUE TITLE
Fatal error: Call to a member function getType() on string in /var/www/html/harleyq/ether-php/src/Ethereum.php on line 102

### ISSUE THREAD

**Issue by marriva** [digitaldonkey/ethereum-php#4]
@digitaldonkey 

ethereumTester.php

`Fatal error: Call to a member function getType() on string in /var/www/html/harleyq/ether-php/src/Ethereum.php on line 102`

`        $args = func_get_args();
        if (count($args) && isset($argument_class_names)) {
          $this->debug('Arguments', $args);

          // Validate arguments.
          foreach ($args as $i => $arg) {

            if ($argument_class_names[$i] !== $arg->getType()) {
              throw new \InvalidArgumentException("Argument $i is " . $arg->getType() . " but expected $argument_class_names[$i] in $method().");
            }
            else {`

how $arg could be EthS object if it is basic function argument?

**Comment by digitaldonkey** [comment]
I don't understand your question nor the Environment. 
Can you provide information how to reproduce this issue?
Which Ethereum Client your are using?

**Comment by erupakov** [comment]
@marriva maybe this code block can help you, I've resolved the issue:
```
require_once 'vendor/autoload.php';
use Ethereum\Ethereum;
use Ethereum\EthBlockParam;
use Ethereum\EthD20;
const GETH_URL = 'http://localhost:8545';
$geth= new Ethereum(GETH_URL);
$ethAddr = new EthD20($address);
$balance = $geth->eth_getBalance($ethAddr,new EthBlockParam());

**Comment by digitaldonkey** [comment]
I added some more examples
https://github.com/digitaldonkey/ethereum-php/blob/dev/public/client-example.php

**Comment by digitaldonkey** [comment]
Should be fixed in dev branch now.
