### ISSUE TITLE
About php version 7.2

### ISSUE THREAD

**Issue by 7-paulwong** [digitaldonkey/ethereum-php#41]
When I tried to composer install this package, it came out an error that said the package requires php >= 7.2, which the composer.json file shows. But the README.md says all php version 7.1+ satisfy the requirement. Do I have to upgrade my php version to 7.2+? Or can you just lower the php version requirement.

**Comment by digitaldonkey** [comment]
Basically I started moving to 7.2 due to it's stronger type system, so the 7.1 is actually the error. 

But I also saw a strong drop in usage, which would be an argument to switch back. I think I'll downgrade requirements the next days.

**Comment by digitaldonkey** [comment]
Downgraded to 7.1
https://github.com/digitaldonkey/ethereum-php/commit/8405fdaf3d3a57ad55ce59fcde87cc4a16235b02
Was actually not worth keeping up 7.2 requirements.
