### ISSUE TITLE
Is this project currently maintained?

### ISSUE THREAD

**Issue by ftppro** [digitaldonkey/ethereum-php#5]
1. Is this project currently maintained?
2. Do I have to open any additional ports on my Linux server?
3. Can I use this API to add transactions to the Ropsten Testnet?

**Comment by murich** [comment]
4. Can I use this to interact via infura server?

**Comment by digitaldonkey** [comment]
Many questions: 
1) Yes. I will have time to work on it again soon. 
2) No. You don't need to run you own Ethereum node. 
3) No. "Add transactions" means "signing with your private key". This is currently out of scope of the library. The first scope of ethereum-php is a "pull data from Ethereum" approach. Please have a look here: http://slides.com/digitaldonkey/drupal-ethereum#/20 But It might be implemented later.
4) Yes.

**Comment by ftppro** [comment]
Is there a PHP ethereum API or SDK that allows you to add transactions?
I don't want to sync, so it must be a light-client.
I don't want to open any additional ports on my Linux server.
I need to add transactions to the Ropsten Testnet.
There can't be any limits to requests (such as 200 requests per hour), and there can't be a monthly fee.

**Comment by digitaldonkey** [comment]
Seems you have a lot of work in front of you :)
