### ISSUE TITLE
extend class  EthDataType

### ISSUE THREAD

**Issue by YuriyBlackFlag** [digitaldonkey/ethereum-php#6]
@digitaldonkey 
Declaration of Ethereum\Transaction::setValue(Ethereum\EthQ $value) should be compatible with Ethereum\EthDataType::setValue($val, array $params = Array)

**Comment by digitaldonkey** [comment]
What changes would you propose?

**Comment by pxgamer** [comment]
That is a PHP type hinting issue (comes up a lot with PHP 7).

The [`EthDataType::setValue()` method](https://github.com/digitaldonkey/ethereum-php/blob/master/src/EthDataType.php#L85) does not type hint any required type for the `$value` variable.
The [`Transaction::setValue()` method](https://github.com/digitaldonkey/ethereum-php/blob/master/src/Transaction.php#L102) type-hints `EthQ` as the required type for the `$value` variable.

Methods that are extended should use the same variables (and type hinting), so you could resolve this by changing the `Transaction::setValue()` method to be like the following:

```php
public function setValue($value, array $params = array()){
```

Then you can add the type-hinting to a PhpDoc comment for that method.
